#load @"system.collections.fsx" 
#load @"system.diagnostics.debug.fsx" 
#load @"system.resources.resourcemanager.fsx" 
#load @"system.runtime.fsx" 
#load @"system.runtime.extensions.fsx" 
#r "System.Core" 