#load @"system.io.fsx" 
#load @"system.io.filesystem.primitives.fsx" 
#load @"system.runtime.fsx" 
#load @"system.runtime.handles.fsx" 
#load @"system.text.encoding.fsx" 
#load @"system.threading.tasks.fsx" 
#r "../../packages/System.IO.FileSystem/lib/net46/System.IO.FileSystem.dll" 