#load @"system.collections.fsx" 
#load @"system.diagnostics.tracing.fsx" 
#load @"system.reflection.fsx" 
#load @"system.runtime.fsx" 
#load @"system.threading.fsx" 
#r "../../packages/System.Diagnostics.DiagnosticSource/lib/net46/System.Diagnostics.DiagnosticSource.dll" 