#load @"system.globalization.fsx" 
#load @"system.resources.resourcemanager.fsx" 
#load @"system.runtime.fsx" 
#load @"system.runtime.extensions.fsx" 
#load @"system.runtime.interopservices.fsx" 
#r "../../packages/System.Globalization.Extensions/lib/net46/System.Globalization.Extensions.dll" 